### ISSUE TITLE
events keeps increassing

### ISSUE THREAD

**Issue by brunooliveiramac** [kuskoman/logstash-exporter#197]
Is the any reason for the events increasing forever?
I mean, there is no event going in or out, but the metrics still show that there is.

![image](https://github.com/kuskoman/logstash-exporter/assets/10716628/d8f34fbf-6491-4db4-b568-d8ef6de5deaa)

Would this be some misconfiguration?
sorry, It is more a question than a real bug.

**Comment by kuskoman** [comment]
Hello @brunooliveiramac 
I will test if the metric is implemented correctly. If I wont be able to replicate the issue I will ask you for more information regarding your configuration

**Comment by brunooliveiramac** [comment]
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
data:
  logstash.conf: |
    input {
      syslog {
        port => 5044
      }
    }
    output {
      kafka {
        topic_id => "syslogs"
        bootstrap_servers => "kafka-dev.gcp.vikingcloud.com:9092"
      }
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:8.9.0
        ports:
        - containerPort: 5044
        - containerPort: 9600
        volumeMounts:
        - name: logstash-config-volume
          mountPath: /usr/share/logstash/pipeline
        # env:
        # - name: "LOG_LEVEL"
        #   value: "debug"
      volumes:
      - name: logstash-config-volume
        configMap:
          name: logstash-configmap
          items:
          - key: logstash.conf
            path: logstash.conf

---

apiVersion: v1
kind: Service
metadata:
  name: logstash-service
  labels:
    app: logstash
spec:
  selector:
    app: logstash
  ports:
    - name: log
      protocol: TCP
      port: 5044
      targetPort: 5044
    - name: prom
      protocol: TCP
      port: 9600
      targetPort: 9600    
```



nothing much, im still testing :D 

exporter values:
```
logstash:
  ## @param logstash.url Logstash instance URL
  ##
  url: "http://logstash-service.vikingcloud.svc.cluster.local:9600"

## @section Image settings
##
image:
  ## @param image.repository Image repository
  ##
  repository: "kuskoman/logstash-exporter"
  ## @param image.tag Image tag, if not set the appVersion is used
  ##
  tag: "v1.5.5"
```
