### ISSUE TITLE
Error "open .env: no such file or directory" when starting the exporter

### ISSUE THREAD

**Issue by pavel-mokrushin** [kuskoman/logstash-exporter#405]
### Description of the Issue

I use Docker Compose with this configuration:
```
services:
  logstash-exporter:
    container_name: logstash-exporter
    image: gcr.io/kuskoman/logstash-exporter:v1.8.3   
   ports:
      - 9198:9198
    volumes:
      - /home/vm-operator/compose_config/logstash-exporter/config.yml:/app/config.yml
    restart: always
```

The configuration file is not applied. I also tried the version "v2.0.0-pre8", the error is the same. 
I can only run on "master"

### Version of logstash-exporter, or logstash-exporter Image

1.8.3

### Operating System/Environment

Debian GNU/Linux 11 (bullseye), Docker 26.1.3

### Logs

```sh
2025/01/04 12:24:15 open .env: no such file or directory
time=2025-01-04T12:24:15.393Z level=INFO msg="Version: v1.8.3, SemanticVersion: unknown, GitCommit: 078156893ad9ccf5b35de9a7240074be6ba4c632, GoVersion: go1.23.1, BuildArch: amd64, BuildOS: linux, BuildDate: 2024-10-14T12:09:35Z"
time=2025-01-04T12:24:15.393Z level=INFO msg="starting server on" host="" port=9198
time=2025-01-04T12:24:31.117Z level=ERROR msg="executor failed" name=nodeinfo duration=420.399µs err="Get \"http://localhost:9600\": dial tcp [::1]:9600: connect: connection refused"
time=2025-01-04T12:24:31.117Z level=ERROR msg="executor failed" name=nodestats duration=1.228695ms err="Get \"http://localhost:9600/_node/stats\": dial tcp [::1]:9600: connect: connection refused"
```

**Comment by satk0** [comment]
Wait, but it started, it's just a warning that you didn't provided .env config file, v2 prioritises yaml (ideally depreciating it in a full release) 😺 

And yes, it is a bit unclear and unnecessary when you already provided yaml config file. That's why master has removed this warning on such a condition. Hope that now it's clear.

**Comment by satk0** [comment]
@pavel-mokrushin oh and v1 only supports .env not yaml as you provided, that's you can't get it running

**Comment by pavel-mokrushin** [comment]
@satk0 thanks
I applied this configuration:
```
services:
  logstash_exporter:
    container_name: logstash_exporter
    image: ghcr.io/kuskoman/logstash-exporter:v1.8.3
    ports:
      - 9198:9198
    environment:
      LOGSTASH_URL: "http://172.16.80.238:9600"
      LOG_LEVEL: info
    # volumes:
    #   - ./config.yml:/app/config.yml
    restart: always
```
Indeed, when I registered the settings in the "environment" section, the settings applied.
It was not clear from the exporter's documentation what exactly should be done at the moment.

In the readme, you could write that for v1, "do it this way", but for v2, "do it differently"
