### ISSUE TITLE
Exporter connect to wrong URLs using by Helm

### ISSUE THREAD

**Issue by chopha66** [kuskoman/logstash-exporter#409]
### Description of the Issue

Hello,
I'm configuring the application by distributing it as Helm Chart to the k8s environment.
After setting the URL as below, update the manifest based on values.yaml

- values.yaml
logstash:
  urls:
    - logstash.namespace:9600
  server:
    host: "0.0.0.0"
    port: 9198
  logging:
    level: "debug"

But check the log at the time of execution, it seems that the call is continuously made to localhost:9600 as below. 
I would appreciate it if you could let me know the solution.

time=2025-02-03T14:55:29.476Z level=ERROR msg="executor failed" name=nodestats duration=1.190619ms err="Get \"http://localhost:9600/_node/stats\": dial tcp [::1]:9600: connect: connection refused"
time=2025-02-03T14:55:29.476Z level=DEBUG msg="collector finished" name=nodestats

### Version of logstash-exporter, or logstash-exporter Image

v2.0.0-pre8

### Version of Chart (if applicable)

2.0.0

### Operating System/Environment

k8s

### Logs

```sh

```

**Comment by chopha66** [comment]
So how do I manually configure config through values.yaml? (such as logstash instance url)

**Comment by kuskoman** [comment]
@knpshkn v1 does not support config.yml file, it uses env vars instead. please refer to v1 branch in the repo

**Comment by kuskoman** [comment]
@chopha66 in the v2 version i renamed urls to instances and forgot to change helm chart. sorry for making breaking changes but this was kinda pourpose of v2 :P 
i was hoping to provide more stable api sooner, but i am simultaneously finishing my engineering thesis and preparing my track motorcycle for the next season therefore have really little time to work on this project RN, i hope it will change soon
@satk0 would you have time to fix that?

**Comment by chopha66** [comment]
v1 doesn't seem to support Env for multiple logstash instances.. 
is it possible to set up for multiple logstash instance URLs?
Logstash for monitoring is currently configured with Replica 6

**Comment by kuskoman** [comment]
@chopha66 version v1 was designed as a sidecar/daemon per instance, so there is no possibility to watch more than one instance. my solution was to deploy exporter along with each of the logstash instances and i think for example cloudflare guys did the same thing.
this design choice was the main reason why i created v2, but i still did not have time to finish it unfortunetely

**Comment by chopha66** [comment]
Thank you for your response!

**Comment by hunter86bg** [comment]
So, how do I specify the version (v1 vs v2) ? What option allows my logstash-exporter pod to connect to all pods ?

I've tried with the following in the helm but the pod tries to use the default http://logstash:9600/
```
logstash:
  urls:
    - "http://ls1.service.namespace.svc.cluster.local:9600"
    - "http://ls2.service.namespace.svc.cluster.local:9600"
    - "http://ls3.service.namespace.svc.cluster.local:9600"
```

I tried by removing logstash.urls and defining deployment.env which properly creates LOGSTASH_URL env variable with all 3 pods (comma separated) without any extra spaces:
```
LOGSTASH_URL:  "http://ls1.service.namespace.svc.cluster.local:9600,\
  http://ls2.service.namespace.svc.cluster.local:9600,\
  http://ls3.service.namespace.svc.cluster.local:9600"
```

But i see in the logs something crazy strange:
```
time=2025-02-28T09:33:02.472Z level=ERROR msg="executor failed" name=nodeinfo duration=122.179µs err="Get \"http://ls1.service.namespace.svc.cluster.local:9600,http//ls2.service.namespace.svc.cluster.local:9600,http://ls3.service.namespace.svc.cluster.local:9600\": dial tcp: lookup ls1.service.namespace.svc.cluster.local:9600,http: no such host"
```

Why it's changing 'http://' to 'http//', I have no idea.

**Comment by hunter86bg** [comment]
I've tried v2 with logstash.urls but it still tries to connect to http://localhost:9600

**Comment by hunter86bg** [comment]
Even with customconfig it's still defaulting to 'http://localhost:9600'
Would V2 work with the env variable ?

**Comment by kuskoman** [comment]
@hunter86bg yup, it should work, and i am not planning to change it, but you must remember that v2 is far from being stable yet, so there may be some changes

**Comment by hunter86bg** [comment]
Sure, I'm deploying on dev right now to have some overview of our logstashes.
Once I have some time, I will try to open a PR as I want to add automatic discovery of logstash pods , use SSL and credentials for the API and many more ;)

**Comment by hunter86bg** [comment]
@kuskoman , it would be nice to bump the version of the chart as some GitOps refuse to pull the chart if the version is the same.

**Comment by kuskoman** [comment]
will do soon

**Comment by hunter86bg** [comment]
I will have to give up.
No matter what it refuses to take the correct urls:


```
 containers:
  - env:
    - name: EXPORTER_CONFIG_LOCATION
      value: /app/config.yml
    image: <private registry>/logstash-exporter:v2.0.0-pre8
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: 9198
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: exporter
    ports:
    - containerPort: 9198
      name: http
      protocol: TCP
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /app/config.yml
      name: config-volume
      subPath: config.yml
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-9wksm
      readOnly: true
<truncated>
  volumes:
  - configMap:
      defaultMode: 420
      name: logstash-exporter
    name: config-volume
<truncated>
```

Configmap data:
```
data:
  config.yml: "logstash:\n  instances:\n    - url: \"http://pod0.service.namespace.svc.cluster.local:9600\"\n
    \   - url: \"http://pod0.service.namespace.svc.cluster.local:9600\"\n
    \   - url: \"http://pod0.service.namespace.svc.cluster.local:9600\"\n
    \   \nserver:\n  host: \"0.0.0.0\"\n  port: 9198\nlogging:\n  level: \"debug\""
```
Which seems to be like this:
```
$ kubectl get configmaps logstash-exporter -o jsonpath='{.data}' | jq -r '.["config.yml"]'
logstash:
  instances:
    - url: "http://pod0.service.namespace.svc.cluster.local:9600"
    - url: "http://pod1.service.namespace.svc.cluster.local:9600"
    - url: "http://pod2.service.namespace.svc.cluster.local:9600"
    
server:
  host: "0.0.0.0"
  port: 9198
logging:
  level: "debug"
```

Logs indicate that ignores the yaml:
```
time=2025-02-28T12:22:45.407Z level=DEBUG msg="executing collector" name=nodestats
time=2025-02-28T12:22:45.407Z level=DEBUG msg="executing collector" name=nodeinfo
time=2025-02-28T12:22:45.408Z level=ERROR msg="executor failed" name=nodeinfo duration=532.88µs err="Get \"http://localhost:9600\": dial tcp 127.0.0.1:9600: connect: connection refused"
time=2025-02-28T12:22:45.408Z level=DEBUG msg="collector finished" name=nodeinfo
time=2025-02-28T12:22:45.408Z level=ERROR msg="executor failed" name=nodestats duration=577.1µs err="Get \"http://localhost:9600/_node/stats\": dial tcp 127.0.0.1:9600: connect: connection refused"
time=2025-02-28T12:22:45.408Z level=DEBUG msg="collector finished" name=nodestats
```

I will give one last attempt with v1.8.4

**Comment by hunter86bg** [comment]
v1.8.4 works when setting up a single pod for LOGSTASH_URL

**Comment by hunter86bg** [comment]
@kuskoman , which branch is v2 ? I want to check how it parses the urls and debug the problem. Creating 10 helmReleases seems a bit too much and I can't use the v1 as sidecar as I don't want to adjust the eck-operator.

**Comment by kuskoman** [comment]
master

**Comment by hunter86bg** [comment]
I've added the v1 container as a sidecar to my Logstash pods (eck-operator). For anyone reading, here is a snippet of the Logstash object:

```
apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
  name: logstash
  namespace: namespace
spec:
  config:
    # disable API SSL for the exporter
    api.auth.type: none
    api.ssl.enabled: false
   <other config options>
  count: <count of logstashes>
  image: <logstash-pod>:8.14.3
  pipelines:
  <truncated>
  podTemplate:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9198"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: logstash
      <truncated>
      - env:
        - name: LOGSTASH_URL
          value: http://localhost:9600
        image: <private-repo>/logstash-exporter:v1.8.4
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 9198
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: logstash-exporter
        ports:
        - containerPort: 9198
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
  # needed as the API SSL was disabled for the exporter
  services:
  - name: api
    tls:
      selfSignedCertificate:
        disabled: true
<truncated>
```
