### ISSUE TITLE
logstash with annotation ignored

### ISSUE THREAD

**Issue by cdino** [kuskoman/logstash-exporter#455]
### Description of the Issue

im testing an early version of the exporter with the controller feature.

This is my helm config:
```
logstash:
  instances: [] #disable instances
  server:
    port: 9198
  logging:
    level: "debug"
kubernetes:
  enabled: true
  resources:
    # Pod monitoring configuration
    pods:
      enabled: true
      annotationPrefix: "logstash-exporter.io"
  resyncPeriod: 10m
  scrapeInterval: 15s
  logstashURLAnnotation: "logstash-exporter.io/url"

serviceAccount:
  create: true
  enabled: true
rbac:
  create: true
deployment:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

image:
  repository: kuskoman/logstash-exporter
  tag: "v2.0.0-pre11"
  pullPolicy: Always

service:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9198"
```

My logstash annotation are:
```
Annotations:
                  logstash-exporter.io: "true"
                  logstash-exporter.io/url: http://${data.host}:9600
```

What i want to achieve is to track al logstashes running on the kubernetes cluster.

But it seems ignored from the logstash-exporter-controller. Attached the logs..

Thx for the great work by the way ;)

### Version of logstash-exporter, or logstash-exporter Image

v2.0.0-pre11

### Version of Chart (if applicable)

master

### Operating System/Environment

v1.29.6+rke2r1

### Logs

```sh
[logstash-exporter-85f56b449d-xsgkt] time=2025-04-19T15:21:24.795Z level=DEBUG msg="watching for config changes is disabled"
[logstash-exporter-85f56b449d-xsgkt] time=2025-04-19T15:21:24.795Z level=DEBUG msg="starting application components"
[logstash-exporter-85f56b449d-xsgkt] time=2025-04-19T15:21:24.795Z level=INFO msg="kubernetes controller is disabled"
[logstash-exporter-85f56b449d-xsgkt] time=2025-04-19T15:21:24.795Z level=DEBUG msg="creating new app server instance" config="{Host:0.0.0.0 Port:9198 TLSConfig:<nil> BasicAuth:<nil> ReadTimeout:0 WriteTimeout:0 MaxConnections:0}"
[logstash-exporter-85f56b449d-xsgkt] time=2025-04-19T15:21:24.795Z level=INFO msg="application initialized"
[logstash-exporter-85f56b449d-xsgkt] time=2025-04-19T15:21:24.795Z level=DEBUG msg="starting server error handler in a separate goroutine"
[logstash-exporter-85f56b449d-xsgkt] time=2025-04-19T15:21:24.795Z level=INFO msg="starting server" host=0.0.0.0 port=9198
[logstash-exporter-85f56b449d-xsgkt] time=2025-04-19T15:22:02.720Z level=DEBUG msg="executing collector" name=nodestats
[logstash-exporter-85f56b449d-xsgkt] time=2025-04-19T15:22:02.720Z level=DEBUG msg="executing collector" name=nodeinfo
[logstash-exporter-85f56b449d-xsgkt] time=2025-04-19T15:22:02.721Z level=ERROR msg="executor failed" name=nodestats duration=1.127731ms err="Get \"http://localhost:9600/_node/stats\": dial tcp [::1]:9600: connect: connection refused"
[logstash-exporter-85f56b449d-xsgkt] time=2025-04-19T15:22:02.721Z level=DEBUG msg="collector finished" name=nodestats
[logstash-exporter-85f56b449d-xsgkt] time=2025-04-19T15:22:02.721Z level=ERROR msg="executor failed" name=nodeinfo duration=1.268611ms err="Get \"http://localhost:9600\": dial tcp [::1]:9600: connect: connection refused"
[logstash-exporter-85f56b449d-xsgkt] time=2025-04-19T15:22:02.721Z level=DEBUG msg="collector finished" name=nodeinfo
[logstash-exporter-85f56b449d-xsgkt] time=2025-04-19T15:22:12.720Z level=DEBUG msg="executing collector" name=nodestats
[logstash-exporter-85f56b449d-xsgkt] time=2025-04-19T15:22:12.720Z level=DEBUG msg="executing collector" name=nodeinfo
[logstash-exporter-85f56b449d-xsgkt] time=2025-04-19T15:22:12.720Z level=ERROR msg="executor failed" name=nodeinfo duration=352.181µs err="Get \"http://localhost:9600\": dial tcp [::1]:9600: connect: connection refused"
```
